/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package dti.g55.wordle

import java.util.Scanner

/**
 * Ceci est une application exécutable pour fins de tests seulement... rien de sérieux ici.
 */
class App {
	val scan = Scanner( System.`in` )
	val motMystère = "RICHE"
	val w = Wordle( motMystère )

	fun démarrer() {
		println("Vous avez 6 essais pour trouver le mot mystère...")
		
		for(tour in 1..6) {
			println()
			print("$tour : ")
			var essai = scan.nextLine()

			val résultat = w.essayer( essai )
			if ( w.estRéussi() ) {
				println("Bravo!")
				break;
			}
			println( résultat )
			println( w.obtenirLettres() )
		} 
	}
}

fun main() {
    App().démarrer()
}
